-- AUTO-GENERATED by scripts/build-setup-sql.mjs — do not edit by hand
-- Target: notioncreativeart_nextjs (anlsellghialszuuvipw)


-- ═══ schema.sql ═══
-- NotionCreativeArt — Supabase schema
-- Run this in Supabase Dashboard → SQL Editor → New query → paste → Run

-- ============================================================
-- PROFILES (extends Supabase auth.users with app-level fields)
-- ============================================================
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text,
  last_name text,
  avatar_url text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

-- Auto-create a profile row whenever someone signs up (Google or email)
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, first_name, last_name, avatar_url)
  values (
    new.id,
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name',
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ============================================================
-- CATEGORIES (Women/Men/Kids-style top nav → Amigurumi/Wearables/Home etc.)
-- ============================================================
create table public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  sort_order int not null default 0
);

-- ============================================================
-- PRODUCTS (digital PDF crochet patterns)
-- ============================================================
create table public.products (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  description text,
  skill_level text check (skill_level in ('beginner','intermediate','advanced')),
  price numeric(10,2) not null,
  compare_at_price numeric(10,2), -- for showing "sale" strike-through price
  category_id uuid references public.categories(id),
  images text[] not null default '{}', -- Supabase Storage public URLs
  pdf_pages int,
  lemon_product_id text,
  lemon_variant_id text not null,
  active boolean not null default true,
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

create index on public.products (category_id);
create index on public.products (active);

-- ============================================================
-- ORDERS (one row per Lemon Squeezy order/webhook)
-- ============================================================
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id),
  lemon_order_id text not null unique,
  customer_email text not null,
  amount numeric(10,2) not null,
  currency text not null default 'USD',
  status text not null default 'pending', -- pending / paid / refunded
  product_ids uuid[] not null default '{}',
  created_at timestamptz not null default now()
);

-- ============================================================
-- PURCHASES (one row per product a user owns — powers "My Patterns")
-- ============================================================
create table public.purchases (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id),
  product_id uuid not null references public.products(id),
  order_id uuid not null references public.orders(id),
  purchase_date timestamptz not null default now(),
  unique (user_id, product_id)
);

-- ============================================================
-- WISHLIST
-- ============================================================
create table public.wishlist (
  user_id uuid not null references auth.users(id),
  product_id uuid not null references public.products(id),
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.purchases enable row level security;
alter table public.wishlist enable row level security;

-- Categories & active products: publicly readable (storefront browsing needs no login)
create policy "public read categories" on public.categories for select using (true);
create policy "public read active products" on public.products for select using (active = true);

-- Profiles: user can read/update only their own row
create policy "read own profile" on public.profiles for select using (auth.uid() = id);
create policy "update own profile" on public.profiles for update using (auth.uid() = id);

-- Orders: user can read only their own orders (writes happen via Edge Function using service_role, bypassing RLS)
create policy "read own orders" on public.orders for select using (auth.uid() = user_id);

-- Purchases: user can read only their own purchases
create policy "read own purchases" on public.purchases for select using (auth.uid() = user_id);

-- Wishlist: user can read/insert/delete only their own rows
create policy "manage own wishlist" on public.wishlist for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Admin override: users with profiles.is_admin = true can do anything on products/categories/orders
create policy "admin manage products" on public.products for all
  using (exists (select 1 from public.profiles where id = auth.uid() and is_admin = true));
create policy "admin manage categories" on public.categories for all
  using (exists (select 1 from public.profiles where id = auth.uid() and is_admin = true));
create policy "admin read all orders" on public.orders for select
  using (exists (select 1 from public.profiles where id = auth.uid() and is_admin = true));


-- ═══ storage-setup.sql ═══
-- Run this AFTER schema.sql, in the same SQL Editor.

-- ============================================================
-- BUCKETS
-- ============================================================
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('patterns', 'patterns', false)  -- private: PDFs are never publicly reachable
on conflict (id) do nothing;

-- ============================================================
-- PRODUCT IMAGES — public read, admin-only write
-- ============================================================
create policy "public read product images"
  on storage.objects for select
  using (bucket_id = 'product-images');

create policy "admin write product images"
  on storage.objects for insert
  with check (
    bucket_id = 'product-images'
    and exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
  );

create policy "admin delete product images"
  on storage.objects for delete
  using (
    bucket_id = 'product-images'
    and exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
  );

-- ============================================================
-- PATTERN PDFs — private. File path convention: patterns/{product_id}.pdf
-- A signed URL can only be generated by:
--   (a) an admin (to upload/manage), or
--   (b) a user who has an actual paid purchase row for that product_id
-- This means the "Download PDF" button on the site can call createSignedUrl()
-- directly from the browser — no extra Edge Function needed — and it will
-- simply fail for anyone who hasn't bought the pattern.
-- ============================================================
create policy "admin write patterns"
  on storage.objects for insert
  with check (
    bucket_id = 'patterns'
    and exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
  );

create policy "admin delete patterns"
  on storage.objects for delete
  using (
    bucket_id = 'patterns'
    and exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
  );

create policy "owner read purchased pattern"
  on storage.objects for select
  using (
    bucket_id = 'patterns'
    and (
      exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
      or exists (
        select 1 from public.purchases
        where purchases.user_id = auth.uid()
          and purchases.product_id::text = split_part(storage.objects.name, '.', 1)
      )
    )
  );


-- ═══ site-settings.sql ═══
-- Run this in Supabase SQL Editor (after schema.sql, storage-setup.sql, seed-categories.sql)

create table public.site_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.site_settings enable row level security;

create policy "public read site settings" on public.site_settings for select using (true);

create policy "admin manage site settings" on public.site_settings for all
  using (exists (select 1 from public.profiles where id = auth.uid() and is_admin = true));

-- Seed with the current hardcoded content, so nothing changes visually until you edit it in /admin
insert into public.site_settings (key, value) values
('hero', '{
  "eyebrow": "DIGITAL PDF PATTERNS",
  "title": "Considered patterns, made to last a season and beyond.",
  "images": [],
  "cta_text": "SHOP ALL PATTERNS",
  "cta_link": "/shop"
}'),
('chapters', '[
  {"level": "beginner", "label": "CHAPTER 01", "title": "Beginner", "copy": "Single crochet, half-double, and foundational shaping. Written slow, with stitch counts you can trust.", "image": "", "link": "/shop?level=beginner"},
  {"level": "intermediate", "label": "CHAPTER 02", "title": "Intermediate", "copy": "Colourwork, garment shaping, and multi-piece construction for hands that already know their hook.", "image": "", "link": "/shop?level=intermediate"},
  {"level": "advanced", "label": "CHAPTER 03", "title": "Advanced", "copy": "Fine-gauge wearables and technical construction, for a practiced hand.", "image": "", "link": "/shop?level=advanced"}
]'),
('categories', '[
  {"name": "Amigurumi", "copy": "Toys and characters, one stitch at a time", "image": "", "link": "/shop/amigurumi"},
  {"name": "Wearables", "copy": "Tops, cardigans and accessories to wear", "image": "", "link": "/shop/wearables"},
  {"name": "Home & Decor", "copy": "Blankets, cushions and pieces for the house", "image": "", "link": "/shop/home-decor"},
  {"name": "Bundles", "copy": "Several patterns, one price", "image": "", "link": "/shop/bundles"}
]');


-- ═══ seed-categories.sql ═══
insert into public.categories (name, slug, sort_order) values
  ('Amigurumi', 'amigurumi', 1),
  ('Wearables', 'wearables', 2),
  ('Home & Decor', 'home-decor', 3),
  ('Bundles', 'bundles', 4);


-- ═══ features-2.sql ═══
-- Run this in Supabase SQL Editor

alter table public.products add column if not exists sold_out boolean not null default false;

insert into public.site_settings (key, value) values
('announcements', '{
  "messages": [
    "FREE PATTERN WITH EVERY FIRST ORDER — CODE FIRSTSTITCH",
    "NEW: BEGINNER-FRIENDLY PATTERNS EVERY WEEK",
    "INSTANT PDF DOWNLOAD — NO WAITING, NO SHIPPING",
    "PATTERNS TESTED TWICE BEFORE THEY GO LIVE"
  ]
}')
on conflict (key) do nothing;

insert into public.site_settings (key, value) values
('social', '{
  "instagram": "",
  "youtube": ""
}')
on conflict (key) do nothing;


-- ═══ cart.sql ═══
-- Run this in Supabase SQL Editor

create table public.cart_items (
  user_id uuid not null references auth.users(id),
  product_id uuid not null references public.products(id),
  added_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

alter table public.cart_items enable row level security;

create policy "manage own cart" on public.cart_items for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- ═══ newsletter.sql ═══
-- Run this in Supabase SQL Editor

create table public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  subscribed_at timestamptz not null default now()
);

alter table public.newsletter_subscribers enable row level security;

-- Anyone (even signed-out visitors) can subscribe
create policy "public can subscribe" on public.newsletter_subscribers for insert
  with check (true);

-- Only admins can view the list
create policy "admin read subscribers" on public.newsletter_subscribers for select
  using (exists (select 1 from public.profiles where id = auth.uid() and is_admin = true));


-- ═══ homepage-layout.sql ═══
-- Run this in Supabase SQL Editor

insert into public.site_settings (key, value) values
('homepage_layout', '[
  {"id": "hero", "label": "Hero Banner", "visible": true},
  {"id": "categories", "label": "Shop by Category", "visible": true},
  {"id": "chapters", "label": "Skill Level Chapters", "visible": true},
  {"id": "trending", "label": "Trending Now", "visible": true},
  {"id": "new_arrivals", "label": "New Arrivals", "visible": true}
]')
on conflict (key) do nothing;


-- ═══ categories-parent-migration.sql ═══
-- Adds parent/subcategory support to categories, and organizes the existing
-- 38 flat categories into 10 main categories with real subcategories under
-- them. Safe to run more than once.

alter table public.categories add column if not exists parent_id uuid references public.categories(id) on delete set null;

-- 3 new main categories (Amigurumi, Wearables, Bags & Totes, Home Decor,
-- Baby & Kids, Seasonal, Bundles already exist as top-level rows).
insert into public.categories (name, slug, sort_order)
select 'Accessories', 'accessories', 5
where not exists (select 1 from public.categories where slug = 'accessories');

insert into public.categories (name, slug, sort_order)
select 'Kitchen & Storage', 'kitchen-storage', 6
where not exists (select 1 from public.categories where slug = 'kitchen-storage');

insert into public.categories (name, slug, sort_order)
select 'Holiday', 'holiday', 9
where not exists (select 1 from public.categories where slug = 'holiday');

-- Assign every subcategory to its main category, matched by slug.
update public.categories set parent_id = (select id from public.categories where slug = 'amigurumi')
where slug in ('wild-animals', 'pet-animals', 'fantasy-mythical-creatures', 'cartoon-kawaii-characters', 'miniature-amigurumi');

update public.categories set parent_id = (select id from public.categories where slug = 'wearables')
where slug in ('tops-outerwear', 'bottoms', 'dresses-jumpsuits');

update public.categories set parent_id = (select id from public.categories where slug = 'accessories')
where slug in ('head-accessories', 'neck-shoulder', 'hand-arm', 'footwear');

update public.categories set parent_id = (select id from public.categories where slug = 'bags-totes')
where slug in ('everyday-bags', 'specialty-bags');

update public.categories set parent_id = (select id from public.categories where slug = 'home-decor')
where slug in ('wall-art-wall-hangings', 'cushions-pillows', 'blankets-throws', 'rugs-mats');

update public.categories set parent_id = (select id from public.categories where slug = 'kitchen-storage')
where slug in ('table-kitchen', 'plant-storage');

update public.categories set parent_id = (select id from public.categories where slug = 'baby-kids')
where slug in ('baby-mobile-patterns', 'nursery-decor-sets', 'growth-chart-patterns', 'sensory-teething-toys', 'play-mat-patterns', 'kids-baby-wearables', 'lovey-security-blanket-combos');

update public.categories set parent_id = (select id from public.categories where slug = 'seasonal')
where slug in ('summer', 'autumn');

update public.categories set parent_id = (select id from public.categories where slug = 'holiday')
where slug in ('ramadan-eid', 'diwali');

-- Bundles stays top-level with no subcategories — nothing to assign.


-- ═══ categories-image-migration.sql ═══
alter table public.categories add column if not exists image text;


-- ═══ billing-address.sql ═══
-- Run this in Supabase SQL Editor

alter table public.profiles add column if not exists billing_country text;
alter table public.profiles add column if not exists billing_zip text;


-- ═══ billing-address-full.sql ═══
-- Run this in Supabase SQL Editor
-- Adds the remaining billing-address fields on top of billing-address.sql
-- (which already added billing_country + billing_zip).

alter table public.profiles add column if not exists billing_address_line1 text;
alter table public.profiles add column if not exists billing_city text;
alter table public.profiles add column if not exists billing_state text;


-- ═══ materials-field.sql ═══
-- Run this in Supabase SQL Editor

alter table public.products add column if not exists materials text;


-- ═══ product-seo-fields.sql ═══
-- Run this in Supabase SQL Editor

alter table public.products add column if not exists meta_title text;
alter table public.products add column if not exists meta_description text;


-- ═══ products-soft-delete-migration.sql ═══
alter table public.products add column if not exists deleted_at timestamptz;


-- ═══ checkout-mode.sql ═══
-- Run this in Supabase SQL Editor

alter table public.products
  add column if not exists checkout_mode text not null default 'overlay'
  check (checkout_mode in ('overlay', 'hosted'));


-- ═══ cart-numeric-variant-id.sql ═══
-- Run this in Supabase SQL Editor

alter table public.products add column if not exists lemon_numeric_variant_id text;


-- ═══ wishlist-count.sql ═══
-- Run this in Supabase SQL Editor

alter table public.products add column if not exists wishlist_count integer not null default 0;

create or replace function public.update_wishlist_count()
returns trigger as $$
begin
  if tg_op = 'INSERT' then
    update public.products set wishlist_count = wishlist_count + 1 where id = new.product_id;
    return new;
  elsif tg_op = 'DELETE' then
    update public.products set wishlist_count = greatest(wishlist_count - 1, 0) where id = old.product_id;
    return old;
  end if;
  return null;
end;
$$ language plpgsql security definer;

drop trigger if exists on_wishlist_change on public.wishlist;
create trigger on_wishlist_change
  after insert or delete on public.wishlist
  for each row execute procedure public.update_wishlist_count();

-- Backfill existing counts from current wishlist rows
update public.products p
set wishlist_count = (select count(*) from public.wishlist w where w.product_id = p.id);


-- ═══ image-pipeline-migration.sql ═══
-- Run this in Supabase SQL Editor (replaces the previous version — that one
-- failed because Postgres couldn't auto-cast the OLD default value to jsonb).
-- IMPORTANT: run this only AFTER deleting your old test product listings.

-- If you still have old products with the old string[] images format, delete them first:
-- delete from public.products;

alter table public.products alter column images drop default;
alter table public.products alter column images type jsonb using '[]'::jsonb;
alter table public.products alter column images set default '[]'::jsonb;


-- ═══ free-pattern-direct-download-migration.sql ═══
alter table public.purchases alter column order_id drop not null;


-- ═══ name-change-cooldown-migration.sql ═══
alter table public.profiles add column if not exists name_changed_at timestamptz;


-- ═══ also-bought-rpc.sql ═══
-- Run this in Supabase SQL Editor
--
-- "Customers Also Bought" needs to look across ALL orders (not just the
-- visitor's own) to find products frequently bought alongside this one —
-- but the "read own orders" RLS policy means a regular customer's browser
-- session can only ever see their own orders. Querying orders.product_ids
-- directly from the client would silently return nothing for everyone
-- except admins.
--
-- This function runs with elevated privilege (security definer) to see
-- every order, but only ever returns a plain array of product ids — no
-- customer names, emails, amounts, or order ids are exposed. Same pattern
-- as product_slug_ever_existed.

create or replace function public.get_also_bought(target_product_id uuid, result_limit int default 8)
returns uuid[]
language sql
security definer
set search_path = public
as $$
  select coalesce(array_agg(product_id order by cnt desc), array[]::uuid[])
  from (
    select pid as product_id, count(*) as cnt
    from public.orders, unnest(product_ids) as pid
    where target_product_id = any(product_ids)
      and pid != target_product_id
    group by pid
    order by cnt desc
    limit result_limit
  ) t
$$;

grant execute on function public.get_also_bought(uuid, int) to anon, authenticated;

-- Same problem, same fix, for the "X+ makers have downloaded this" trust
-- badge: "read own purchases" RLS means a regular customer's browser can
-- only ever count their own purchase of a product (0 or 1) — never the real
-- total across everyone. This returns just a count, nothing else.

create or replace function public.get_purchase_count(target_product_id uuid)
returns int
language sql
security definer
set search_path = public
as $$
  select count(*)::int from public.purchases where product_id = target_product_id
$$;

grant execute on function public.get_purchase_count(uuid) to anon, authenticated;



-- ═══ product-slug-existence-check.sql ═══
-- Run this in Supabase SQL Editor
-- Lets the product page tell "this URL never existed" apart from "this
-- pattern existed but was deactivated/deleted" — without exposing any
-- product data to non-admin visitors (RLS still fully applies to the
-- products table itself; this only returns a boolean).

create or replace function public.product_slug_ever_existed(check_slug text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists(select 1 from public.products where slug = check_slug);
$$;

grant execute on function public.product_slug_ever_existed(text) to anon, authenticated;


-- ═══ purchases-unique-constraint-fix.sql ═══
-- schema.sql defines `unique (user_id, product_id)` on purchases, but this
-- constraint is missing from the live database (confirmed via error 42P10:
-- "there is no unique or exclusion constraint matching the ON CONFLICT
-- specification"). Adding it now for real duplicate-prevention at the
-- database level.
--
-- A few duplicate (user_id, product_id) rows already exist from earlier
-- failed free-download attempts (before this was fixed) — clean those up
-- first, keeping the earliest row per pair, or the constraint can't be
-- created.
-- Skipped entirely when public.purchases does not exist yet (run full-setup.sql first).

do $$
begin
  if not exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'purchases'
  ) then
    raise notice 'Skipping purchases-unique-constraint-fix: public.purchases does not exist yet.';
    return;
  end if;

  delete from public.purchases a
  using public.purchases b
  where a.user_id = b.user_id
    and a.product_id = b.product_id
    and a.purchase_date > b.purchase_date;

  if not exists (
    select 1 from pg_constraint where conname = 'purchases_user_id_product_id_key'
  ) then
    alter table public.purchases
      add constraint purchases_user_id_product_id_key unique (user_id, product_id);
  end if;
end $$;


-- ═══ purchases-insert-policy-free-only.sql ═══
-- purchases only ever had a SELECT policy ("read own purchases") — there was
-- never an INSERT policy at all, so the free-pattern direct-download flow's
-- client-side upsert into purchases was silently blocked by RLS from the
-- start (the upsert call doesn't check for errors, so this went unnoticed).
-- The old, overly-broad storage policy masked the symptom by letting
-- signed URLs succeed regardless; the new ownership-checking storage policy
-- correctly exposed it, since no real purchases row ever existed.
--
-- This lets a signed-in user insert a purchases row for themselves — but
-- ONLY when the target product is actually free (price = 0), so this can't
-- be used to "claim" a paid pattern without going through checkout. Paid
-- purchases are still created exclusively by the lemon-webhook Edge
-- Function, which uses the service-role key and bypasses RLS entirely —
-- this policy has no effect on that path.

drop policy if exists "users can claim free patterns" on public.purchases;

create policy "users can claim free patterns"
on public.purchases for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.products
    where products.id = purchases.product_id
    and products.price = 0
  )
);


-- ═══ CRITICAL-fix-profile-privilege-escalation.sql ═══
-- CRITICAL: the original "update own profile" policy only checked that a
-- user was updating their OWN row (auth.uid() = id) — it never restricted
-- WHICH columns they could change. Any signed-up customer could call
-- `supabase.from('profiles').update({ is_admin: true }).eq('id', <self>)`
-- from the browser and grant themselves full admin access.
--
-- This replaces it with a WITH CHECK clause that blocks is_admin from
-- being changed through this self-service path — it must stay exactly
-- what it already was. Every other profile field (name, billing address,
-- phone, etc.) is still freely self-editable as before. is_admin can still
-- be changed by you directly via Supabase Dashboard → Table Editor (which
-- uses a privileged connection that bypasses RLS entirely).

drop policy if exists "update own profile" on public.profiles;

create policy "update own profile" on public.profiles for update
  using (auth.uid() = id)
  with check (
    auth.uid() = id
    and is_admin = (select p.is_admin from public.profiles p where p.id = auth.uid())
  );


-- ═══ patterns-bucket-read-policy-v2-secure.sql ═══
-- The previous policy (patterns-bucket-read-policy.sql) let ANY signed-in
-- user generate a signed URL for ANY file in the 'patterns' bucket — the
-- app's own UI only showed download links to people who'd actually bought
-- (or claimed, for free items) the pattern, but that check lived only in
-- the browser, not in the database. Anyone could open dev tools and call
-- createSignedUrl() directly with a product id they never purchased.
--
-- This replaces it with a real ownership check: a signed URL for
-- "<product_id>.pdf" only succeeds if the requesting user has a matching
-- row in purchases, or is an admin (needed for the admin "Test download"
-- button, which checks arbitrary products regardless of purchase history).

drop policy if exists "authenticated users can read patterns" on storage.objects;
drop policy if exists "read own purchased patterns or admin" on storage.objects;

create policy "read own purchased patterns or admin"
on storage.objects for select
to authenticated
using (
  bucket_id = 'patterns'
  and (
    exists (
      select 1 from public.purchases
      where purchases.user_id = auth.uid()
      and purchases.product_id = (regexp_replace(storage.objects.name, '\.pdf$', ''))::uuid
    )
    or exists (
      select 1 from public.profiles
      where profiles.id = auth.uid()
      and profiles.is_admin = true
    )
  )
);


-- ═══ fix-null-images.sql ═══
-- Run this in Supabase SQL Editor
-- Fixes: products.images became NULL for some rows during the earlier
-- schema changes (text[] -> jsonb -> text[] rollback), which crashed the
-- admin product list (and potentially customer-facing pages) wherever code
-- assumed images was always at least an empty array.

update public.products set images = '{}' where images is null;
alter table public.products alter column images set not null;


-- ═══ fix-google-profile-names.sql ═══
-- Run this in Supabase SQL Editor.
-- Fixes: Google sign-ins were getting a blank profile name, because Google
-- populates raw_user_meta_data with given_name/family_name/full_name/name,
-- not the first_name/last_name keys our email-signup flow uses.

create or replace function public.handle_new_user()
returns trigger as $$
declare
  full_name text;
begin
  full_name := new.raw_user_meta_data->>'full_name';
  if full_name is null then
    full_name := new.raw_user_meta_data->>'name';
  end if;

  insert into public.profiles (id, first_name, last_name, avatar_url)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'first_name',
      new.raw_user_meta_data->>'given_name',
      split_part(full_name, ' ', 1)
    ),
    coalesce(
      new.raw_user_meta_data->>'last_name',
      new.raw_user_meta_data->>'family_name',
      nullif(substring(full_name from position(' ' in full_name) + 1), '')
    ),
    coalesce(
      new.raw_user_meta_data->>'avatar_url',
      new.raw_user_meta_data->>'picture'
    )
  );
  return new;
end;
$$ language plpgsql security definer;

-- One-time backfill for accounts (like your own test account) created before this fix,
-- pulling from their Google metadata that's already stored in auth.users:
update public.profiles p
set
  first_name = coalesce(p.first_name, coalesce(u.raw_user_meta_data->>'given_name', split_part(u.raw_user_meta_data->>'full_name', ' ', 1), split_part(u.raw_user_meta_data->>'name', ' ', 1))),
  last_name = coalesce(p.last_name, coalesce(u.raw_user_meta_data->>'family_name', nullif(substring(u.raw_user_meta_data->>'full_name' from position(' ' in u.raw_user_meta_data->>'full_name') + 1), '')))
from auth.users u
where p.id = u.id and (p.first_name is null or p.last_name is null);


-- ═══ fix-repurchase-overwrite.sql ═══
-- Run this in Supabase SQL Editor
-- Fixes: buying the same pattern a second time overwrote the first purchase's
-- order reference instead of creating a second, separate order entry.

do $$
begin
  if not exists (
    select 1 from information_schema.tables
    where table_schema = 'public' and table_name = 'purchases'
  ) then
    raise notice 'Skipping fix-repurchase-overwrite: public.purchases does not exist yet.';
    return;
  end if;

  alter table public.purchases drop constraint if exists purchases_user_id_product_id_key;

  if not exists (
    select 1 from pg_constraint where conname = 'purchases_order_id_product_id_key'
  ) then
    alter table public.purchases
      add constraint purchases_order_id_product_id_key unique (order_id, product_id);
  end if;
end $$;


-- ═══ cascade-product-delete.sql ═══
-- Run this in Supabase SQL Editor
-- Fixes: deleting an old product failed silently/with an error, because
-- wishlist/cart_items/purchases rows referencing it blocked the delete
-- (a foreign-key protection, working as intended — this migration removes
-- that protection on purpose since he's in test phase and wants full deletes
-- to actually work everywhere).

do $$
declare
  con record;
begin
  -- wishlist.product_id -> products.id
  for con in
    select conname from pg_constraint
    where conrelid = 'public.wishlist'::regclass
      and confrelid = 'public.products'::regclass
      and contype = 'f'
  loop
    execute format('alter table public.wishlist drop constraint %I', con.conname);
  end loop;
  alter table public.wishlist
    add constraint wishlist_product_id_fkey
    foreign key (product_id) references public.products(id) on delete cascade;

  -- cart_items.product_id -> products.id
  for con in
    select conname from pg_constraint
    where conrelid = 'public.cart_items'::regclass
      and confrelid = 'public.products'::regclass
      and contype = 'f'
  loop
    execute format('alter table public.cart_items drop constraint %I', con.conname);
  end loop;
  alter table public.cart_items
    add constraint cart_items_product_id_fkey
    foreign key (product_id) references public.products(id) on delete cascade;

  -- purchases.product_id -> products.id
  for con in
    select conname from pg_constraint
    where conrelid = 'public.purchases'::regclass
      and confrelid = 'public.products'::regclass
      and contype = 'f'
  loop
    execute format('alter table public.purchases drop constraint %I', con.conname);
  end loop;
  alter table public.purchases
    add constraint purchases_product_id_fkey
    foreign key (product_id) references public.products(id) on delete cascade;
end $$;


-- ═══ rate-limit-table.sql ═══
-- Generic rate-limit event log — Edge Functions insert a row per attempt and
-- check how many rows exist for a given key within a time window before
-- allowing an action. No RLS policies needed here: only Edge Functions
-- (using the service-role key) ever touch this table, never the browser
-- directly.

create table if not exists public.rate_limit_events (
  id bigserial primary key,
  key text not null,
  created_at timestamptz not null default now()
);

create index if not exists rate_limit_events_key_created_at_idx
  on public.rate_limit_events (key, created_at);

-- Housekeeping: old rows are cheap to accumulate but no longer useful once
-- their window has passed. Safe to run manually any time; nothing depends
-- on rows older than a day for any current rate limit window.
delete from public.rate_limit_events where created_at < now() - interval '1 day';


-- ═══ newsletter-close-direct-insert.sql ═══
-- Newsletter signups now go through the 'subscribe-newsletter' Edge
-- Function, which enforces real server-side rate limiting before inserting.
-- The old "public can subscribe" policy let ANY client insert directly via
-- the Supabase REST API, completely bypassing that rate limit — a spam
-- script could just skip the Edge Function and hit the table directly.
--
-- This removes that open policy. The Edge Function still works because it
-- uses the service-role key, which bypasses RLS entirely. Admin read access
-- is untouched.

drop policy if exists "public can subscribe" on public.newsletter_subscribers;


-- ═══ catchup-migration.sql ═══
-- Run this in Supabase SQL Editor — safe to run even if some of these
-- already exist (everything uses IF NOT EXISTS / safe defaults).
-- This is a catch-up migration covering everything added across this
-- project's session, in case any individual file was missed.

-- Fixes the current "can't add/edit/delete products" crash:
update public.products set images = '{}' where images is null;
alter table public.products alter column images set not null;

alter table public.products add column if not exists sold_out boolean not null default false;
alter table public.products add column if not exists checkout_mode text not null default 'overlay';
alter table public.products add column if not exists materials text;
alter table public.products add column if not exists lemon_numeric_variant_id text;
alter table public.products add column if not exists wishlist_count integer not null default 0;

alter table public.profiles add column if not exists billing_country text;
alter table public.profiles add column if not exists billing_zip text;

-- Re-create the wishlist_count trigger (safe to re-run)
create or replace function public.update_wishlist_count()
returns trigger as $$
begin
  if tg_op = 'INSERT' then
    update public.products set wishlist_count = wishlist_count + 1 where id = new.product_id;
    return new;
  elsif tg_op = 'DELETE' then
    update public.products set wishlist_count = greatest(wishlist_count - 1, 0) where id = old.product_id;
    return old;
  end if;
  return null;
end;
$$ language plpgsql security definer;

drop trigger if exists on_wishlist_change on public.wishlist;
create trigger on_wishlist_change
  after insert or delete on public.wishlist
  for each row execute procedure public.update_wishlist_count();

update public.products p
set wishlist_count = (select count(*) from public.wishlist w where w.product_id = p.id)
where p.wishlist_count = 0;


-- ═══ grants-api-access.sql ═══
-- Ensure Supabase REST API (anon/authenticated) can read public tables after manual SQL setup.
grant usage on schema public to anon, authenticated, service_role;
grant select on all tables in schema public to anon, authenticated;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

alter default privileges in schema public grant select on tables to anon, authenticated;
alter default privileges in schema public grant all on tables to service_role;

notify pgrst, 'reload schema';


-- ═══ seed-initial-data.sql ═══
-- Initial seed data for notioncreativeart_nextjs (NEW independent database)
-- Safe to re-run — uses ON CONFLICT / IF NOT EXISTS patterns.

-- Announcements bar
insert into public.site_settings (key, value) values
  ('announcements', '{"messages":["FREE PATTERN WITH EVERY FIRST ORDER — CODE FIRSTSTITCH"]}'::jsonb)
on conflict (key) do update set value = excluded.value;

-- Hero section
insert into public.site_settings (key, value) values
  ('hero', '{
    "eyebrow": "CROCHET PATTERNS FOR EVERY MAKER",
    "title": "Beautiful Patterns. Made for You.",
    "images": ["/hero-bunny.jpg"],
    "cta_text": "Shop Patterns",
    "cta_link": "/shop/new",
    "secondary_cta_text": "Explore Free Patterns",
    "secondary_cta_link": "/shop?price=free"
  }'::jsonb)
on conflict (key) do update set value = excluded.value;

-- Homepage layout (section order)
insert into public.site_settings (key, value) values
  ('homepage_layout', '[
    {"id":"hero","label":"Hero","visible":true},
    {"id":"trust","label":"Trust Bar","visible":true},
    {"id":"categories","label":"Categories","visible":true},
    {"id":"chapters","label":"Skill Chapters","visible":true},
    {"id":"trending","label":"Featured","visible":true},
    {"id":"new_arrivals","label":"New Arrivals","visible":true},
    {"id":"skill_browse","label":"Skill Browse","visible":true},
    {"id":"free_patterns","label":"Free Patterns","visible":true},
    {"id":"bundles","label":"Bundles","visible":true},
    {"id":"why_us","label":"Why Us","visible":true},
    {"id":"testimonials","label":"Testimonials","visible":true},
    {"id":"newsletter","label":"Newsletter","visible":true}
  ]'::jsonb)
on conflict (key) do update set value = excluded.value;

-- Skill level chapters
insert into public.site_settings (key, value) values
  ('chapters', '[
    {"level":"beginner","label":"CHAPTER 01","title":"Beginner","copy":"Single crochet, half-double, and foundational shaping.","image":"","link":"/shop?level=beginner"},
    {"level":"intermediate","label":"CHAPTER 02","title":"Intermediate","copy":"Colourwork, garment shaping, and multi-piece construction.","image":"","link":"/shop?level=intermediate"},
    {"level":"advanced","label":"CHAPTER 03","title":"Advanced","copy":"Fine-gauge wearables and technical construction.","image":"","link":"/shop?level=advanced"}
  ]'::jsonb)
on conflict (key) do update set value = excluded.value;

-- Extra categories (parent + subcategories for mega menu)
insert into public.categories (name, slug, sort_order, parent_id) values
  ('Baby & Kids', 'baby-kids', 4, null),
  ('Seasonal & Holiday', 'seasonal', 5, null),
  ('Accessories', 'accessories', 6, null),
  ('Tools & Guides', 'tools-guides', 7, null)
on conflict (slug) do nothing;

-- Subcategories under Amigurumi
insert into public.categories (name, slug, sort_order, parent_id)
select 'Wild Animals', 'wild-animals', 1, id from public.categories where slug = 'amigurumi'
on conflict (slug) do nothing;

insert into public.categories (name, slug, sort_order, parent_id)
select 'Pet Animals', 'pet-animals', 2, id from public.categories where slug = 'amigurumi'
on conflict (slug) do nothing;

-- Make first user admin (replace email after signup):
-- update public.profiles set is_admin = true where id = (select id from auth.users where email = 'your@email.com');

