-- Run this AFTER schema.sql, in the same SQL Editor.

-- ============================================================
-- BUCKETS
-- ============================================================
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('patterns', 'patterns', false)  -- private: PDFs are never publicly reachable
on conflict (id) do nothing;

-- ============================================================
-- PRODUCT IMAGES — public read, admin-only write
-- ============================================================
create policy "public read product images"
  on storage.objects for select
  using (bucket_id = 'product-images');

create policy "admin write product images"
  on storage.objects for insert
  with check (
    bucket_id = 'product-images'
    and exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
  );

create policy "admin delete product images"
  on storage.objects for delete
  using (
    bucket_id = 'product-images'
    and exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
  );

-- ============================================================
-- PATTERN PDFs — private. File path convention: patterns/{product_id}.pdf
-- A signed URL can only be generated by:
--   (a) an admin (to upload/manage), or
--   (b) a user who has an actual paid purchase row for that product_id
-- This means the "Download PDF" button on the site can call createSignedUrl()
-- directly from the browser — no extra Edge Function needed — and it will
-- simply fail for anyone who hasn't bought the pattern.
-- ============================================================
create policy "admin write patterns"
  on storage.objects for insert
  with check (
    bucket_id = 'patterns'
    and exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
  );

create policy "admin delete patterns"
  on storage.objects for delete
  using (
    bucket_id = 'patterns'
    and exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
  );

create policy "owner read purchased pattern"
  on storage.objects for select
  using (
    bucket_id = 'patterns'
    and (
      exists (select 1 from public.profiles where id = auth.uid() and is_admin = true)
      or exists (
        select 1 from public.purchases
        where purchases.user_id = auth.uid()
          and purchases.product_id::text = split_part(storage.objects.name, '.', 1)
      )
    )
  );
